spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:postgresql://localhost:5432/shopdb
    username: shop
    password: shop123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8085

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.authentication.dao.DaoAuthenticationProvider: TRACE
